apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hpecpconfigs.hpecp.hpe.com
spec:
  group: hpecp.hpe.com
  version: v1
  names:
    kind: HPECPConfig
    listKind: HPECPConfigList
    plural: hpecpconfigs
    singular: hpecpconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      required: [apiVersion, kind, metadata]
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
              pattern: '^hpecp-global-config$'
        spec:
          type: object
          nullable: true
          properties:
            mgmtSessionSecretName:
              type: string
            fsMount:
              type: object
              nullable: true
              required: [enabled]
              properties:
                enabled:
                  type: boolean
                hostPath:
                  type: string
                  pattern: '^/'
            unrestrictedFsMountNamespaces:
              type: array
              items:
                type: string
                minLength: 1
                maxLength: 63
                pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
        status:
          type: object
          nullable: true
          properties:
            generationUID:
              type: string
            state:
              type: string
            fsMount:
              type: object
              nullable: true
              properties:
                daemonsetNamespace:
                  type: string
                daemonsetName:
                  type: string
                daemonsetReady:
                  type: boolean
                systemPodPreset:
                  type: string
