kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubedirector
rules:
- apiGroups:
  - kubedirector.hpe.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - pods/exec
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - "get"
  - "create"

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubedirector

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubedirector
subjects:
- kind: ServiceAccount
  name: kubedirector
  namespace: hpecp
roleRef:
  kind: ClusterRole
  name: kubedirector
  apiGroup: rbac.authorization.k8s.io
